version: '3'

services:
  node:
    build: ./docker/node
    ports:
      - "4200:4200"
    volumes:
      - ".:/src"
    working_dir: /src
    tty: true
    # command: bash -c "npm install && npm run dev"
    # command: bash -c "npm install && npm run"